[build-system]
requires = ["setuptools", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"


[project]
name = "nio-bot"
description = "Making matrix bots simple"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.11"
license = { text = "GNU GPLv3" }
authors = [
    {name = "Nexus", email = "packages@nexy7574.co.uk"}
]
dynamic = ["version", "dependencies"]
optional-dependencies = { e2ee = ['matrix-nio[e2e]'], cli = ['httpx'] }

[project.scripts]
niocli = "niobot.__main__:cli_root [cli]"

[tool.setuptools_scm]
write_to = "src/niobot/__version__.py"

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}